### ISSUE TITLE
Support server side rendering and do not read window.pageYOffset if window not available

### ISSUE THREAD

**Issue by albertstill** [sampennington/react-scroll-tracker#3]
This [line](https://github.com/sampennington/react-scroll-tracker/blob/137a0b77396058bb0a669bc3e3e46951a007b43e/src/useScrollTracker.ts#L13) causes a server side rendering issue when rendering React on the server. If you checked for the presence of window before reading `window.pageYOffset` and defaulted to 0 if not available I think it would be fine? `window.pageYOffset` is 0 on initial page load anyway. Thanks for the library it's great!

**Comment by albertstill** [comment]
Happy to do the PR if you think this is a good approach

**Comment by sampennington** [comment]
If you would be happy to do a PR that'd be awesome! I have very little experience with server side rendering

**Comment by sampennington** [comment]
But that sounds reasonable
