### ISSUE TITLE
Transpiled code contains an arrow function causing issues on older browsers

### ISSUE THREAD

**Issue by albertstill** [sampennington/react-scroll-tracker#4]
We hit an issue with the transpiled src code when we required this module, it contained an arrow function that broke IE11, we had to whitelist our babel config to transpile it. Was this intentional or do you want to change `tsconfig.json` to transpile arrow functions? Thanks

**Comment by sampennington** [comment]
Hey, this wasn't intentional, try upgrading to 1.4
